window.json_data = {
    "directories" : [
        {
            "name" : "movies",
            "movies" : [
                {
                    "name" : "Wall E",
                    "type" : "hollywood",
                    "year" : 2008,
                    "lang" : ["hindi"],
                    "file_name" : "Wall E (Hindi) - Blu-Ray - 720p - x264 - [Armaan].mkv",
                    "ext" : "mkv",
                    "file_size" : 519050132,
                    "length" : 95,
                    "img" : "img/wall-e.jpg",
                    "imdb_rate" : 8.4
                },
                {
                    "name" : "Thor 2",
                    "type" : "hollywood",
                    "year" : 2013,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Thor 2 - The Dark World (2013) BRRip [Dual Audio - Eng+Hindi].mkv",
                    "ext" : "mkv",
                    "file_size" : 463237996,
                    "length" : 112,
                    "img" : "img/thor-2.jpg",
                    "imdb_rate" : 7.1
                },
                {
                    "name" : "The Social Network",
                    "type" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english"],
                    "file_name" : "The Social Network (2010) 1080p BrRip x264 - 1.2GB - YIFY.mp4",
                    "ext" : "mp4",
                    "file_size" : 1289138071,
                    "length" : 120,
                    "img" : "img/the-social-network.jpg",
                    "imdb_rate" : 7.8
                },
                {
                    "name" : "American Gangster",
                    "type" : "hollywood",
                    "year" : 2007,
                    "lang" : ["english", "hindi"],
                    "file_name" : "American Gangster (2007) UNRATED 720p BRRip [Dual-Audio] [Eng-Hindi] TeamTNT ExClusive.mkv",
                    "ext" : "mkv",
                    "file_size" : 1254288727,
                    "length" : 175,
                    "img" : "img/american-gangster.jpg",
                    "imdb_rate" : 7.8
                },
                {
                    "name" : "Saving Private Ryan",
                    "type" : "hollywood",
                    "year" : 1998,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Saving Private Ryan.1998.720p.Hindi.Eng.Dual Audio[~HFR~].mkv",
                    "ext" : "mkv",
                    "file_size" : 1065589921,
                    "length" : 168,
                    "img" : "img/saving-private-ryan.jpg",
                    "imdb_rate" : 8.6
                },
                {
                    "name" : "The Karate Kid",
                    "type" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english", "hindi"],
                    "file_name" : "The Karate Kid [2010] 720p BRRip [Dual Audio] [English + Hindi] AAC x264 BUZZccd [WBRG].mkv",
                    "ext" : "mkv",
                    "file_size" : 1096872197,
                    "length" : 140,
                    "img" : "img/the-karate-kid.jpg",
                    "imdb_rate" : 6.2
                },
                {
                    "name" : "Coraline",
                    "type" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english"],
                    "file_name" : "[9movies.co.cc]Coraline.2009.DVDRip.x264.scOrp.mkv",
                    "ext" : "mkv",
                    "file_size" : 313362357,
                    "length" : 95,
                    "img" : "img/coraline.jpg",
                    "imdb_rate" : 7.7
                },
                {
                    "name" : "Ninja Assassin",
                    "type" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Ninja.Hindi_Eng.mkv",
                    "ext" : "mkv",
                    "file_size" : 541865453,
                    "length" : 98,
                    "img" : "img/ninja-assassin.jpg",
                    "imdb_rate" : 6.4
                },
                {
                    "name" : "Step Up 2 The Streets",
                    "type" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english"],
                    "file_name" : "Step Up 2 The Streets 2008.720p.x264.BRRip.GokU61.mp4",
                    "ext" : "mp4",
                    "file_size" : 712915027,
                    "length" : 97,
                    "img" : "img/step-Up-2-The-Streets.jpg",
                    "imdb_rate" : 6.2
                },
                {
                    "name" : "The Shawshank Redemption",
                    "type" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english"],
                    "file_name" : "The.Shawshank.Redemption.1994.1080p.x264.YIFY.mp4",
                    "ext" : "mp4",
                    "file_size" : 1722009470,
                    "length" : 142,
                    "img" : "img/the-shawshank-redemption.jpg",
                    "imdb_rate" : 9.3
                },
                {
                    "name" : "127 Hours",
                    "type" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english"],
                    "file_name" : "127.HRSCR-xvid_MC8.avi",
                    "ext" : "avi",
                    "file_size" : 734978048,
                    "length" : 92,
                    "img" : "img/127-hours.jpg",
                    "imdb_rate" : 7.6
                },
                {
                    "name" : "Fearless",
                    "type" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english"],
                    "file_name" : "2006 - Jet.Li.Fearless.cd1-Eng.avi",
                    "ext" : "avi",
                    "file_size" : 734109696+734449664,
                    "length" : 104,
                    "img" : "img/fearless.jpg",
                    "imdb_rate" : 7.7
                },
                {
                    "name" : "Saathiya",
                    "type" : "bollywood",
                    "year" : 2002,
                    "lang" : ["hindi"],
                    "file_name" : "Saathiya 2002 DVDrip XviD MP3 [RangerTD].avi",
                    "ext" : "avi",
                    "file_size" : 723744430,
                    "length" : 132,
                    "img" : "img/saathiya.jpg",
                    "imdb_rate" : 3.7
                },
                {
                    "name" : "300",
                    "type" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english", "hindi"],
                    "file_name" : "300(2006)1080p[Dual Audio] [Eng-Hindi]Current_HD.mkv",
                    "ext" : "mkv",
                    "file_size" : 846027224,
                    "length" : 116,
                    "img" : "img/300.jpg",
                    "imdb_rate" : 7.8
                },
                {
                    "name" : "Spider Man",
                    "type" : "hollywood",
                    "year" : 2002,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Spider Man (2002).avi",
                    "ext" : "avi",
                    "file_size" : 945511668,
                    "length" : 116,
                    "img" : "img/spider-man.jpg",
                    "imdb_rate" : 7.3
                },
                {
                    "name" : "Fast and Furious 3 Tokyo Drift",
                    "type" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english", "hindi"],
                    "file_name" : "OnlineMoviesFreee.Com.Fat.Furious.2006 (1).mkv",
                    "ext" : "mkv",
                    "file_size" : 666625361,
                    "length" : 97,
                    "img" : "img/fast-and-furious-3-tokyo-drift.jpg",
                    "imdb_rate" : 5.9
                },
                {
                    "name" : "Titanic",
                    "type" : "hollywood",
                    "year" : 1997,
                    "lang" : ["hindi"],
                    "file_name" : "Titanic.1997.mkv",
                    "ext" : "mkv",
                    "file_size" : 570760738,
                    "length" : 186,
                    "img" : "img/titanic.jpg",
                    "imdb_rate" : 7.7
                },
                {
                    "name" : "Wanted",
                    "type" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Wanted.mkv",
                    "ext" : "mkv",
                    "file_size" : 828850725,
                    "length" : 105,
                    "img" : "img/wanted.jpg",
                    "imdb_rate" : 6.7
                },
                {
                    "name" : "King Kong",
                    "type" : "hollywood",
                    "year" : 2005,
                    "lang" : ["english", "hindi"],
                    "file_name" : "King Kong 2005 Extended BRRip 720p{Dual audio}[Eng Hindi]Current_HD.mkv",
                    "ext" : "mkv",
                    "file_size" : 1078086425,
                    "length" : 192,
                    "img" : "img/king-kong.jpg",
                    "imdb_rate" : 7.3
                },
                {
                    "name" : "PK",
                    "type" : "bollywood",
                    "year" : 2014,
                    "lang" : ["hindi"],
                    "file_name" : "PK (2014) - 720p - mHD - x264 - AC3 - 5.1 - NonRetail - Hindi ~ Cool_Release.mkv",
                    "ext" : "mkv",
                    "file_size" : 1763774283,
                    "length" : 152,
                    "img" : "img/pk.jpg",
                    "imdb_rate" : 8.4
                },
                {
                    "name" : "Rebel",
                    "type" : "tollywood",
                    "year" : 2012,
                    "lang" : ["hindi", "other"],
                    "file_name" : "Rebel (2012)  m-HD  720p  Hindi  Telugu  BHATTI87.mkv",
                    "ext" : "mkv",
                    "file_size" : 2823101205,
                    "length" : 170,
                    "img" : "img/rebel.jpg",
                    "imdb_rate" : 4.1
                },
                {
                    "name" : "Rock On!!",
                    "type" : "bollywood",
                    //"year" : 0,
                    "lang" : ["hindi"],
                    "file_name" : "Rock On!!.mkv",
                    "ext" : "mkv",
                    "file_size" : 2346834825,
                    "length" : 145,
                    "img" : "img/rock-on.jpg",
                    "imdb_rate" : 7.9
                },
                {
                    "name" : "Risky Business",
                    "type" : "hollywood",
                    "year" : 1983,
                    "lang" : ["english"],
                    "file_name" : "Risky Business 1983 DvDrip[Eng]-greenbud1969.avi",
                    "ext" : "avi",
                    "file_size" : 734330880,
                    "length" : 160,
                    "img" : "img/risky-business.jpg",
                    "imdb_rate" : 6.8
                },
                {
                    "name" : "Dil Dhadakne Do",
                    "type" : "bollywood",
                    "year" : 2015,
                    "lang" : ["hindi"],
                    "file_name" : "Dil Dhadakne Do (2015).mp4",
                    "ext" : "mp4",
                    "file_size" : 943660640,
                    "length" : 162,
                    "img" : "img/dil-dhadakne-do.jpg",
                    "imdb_rate" : 6.9
                },
                {
                    "name" : "Tanu Weds Manu Returns",
                    "type" : "bollywood",
                    "year" : 2015,
                    "lang" : ["hindi"],
                    "file_name" : "Tanu Weds Manu Returns (2015).mkv",
                    "ext" : "mkv",
                    "file_size" : 723432159,
                    "length" : 128,
                    "img" : "img/tanu-weds-manu-returns.jpg",
                    "imdb_rate" : 8.3
                }
            ]
        }
    ]
};
