window.json_data = {
    "directories" : [
        {
            "name" : "hollywood",
            "movies" : [
                {
                    "name" : "Wall E",
                    "region" : "hollywood",
                    "types" : ["animation"],
                    "year" : 2008,
                    "lang" : ["hindi"],
                    "file_name" : "Wall E (Hindi)/Wall E (Hindi) - Blu-Ray - 720p - x264 - [Armaan].mkv",
                    "ext" : "mkv",
                    "file_size" : 519050132,
                    "length" : 95,
                    "img" : "img/wall-e.jpg",
                    "imdb_rate" : 8.4,
                    "imdb_id" : "tt0910970",
                    "quality" : {"video" : "hd"}
                    //"subtitles" : true
                },
                {
                    "name" : "Thor: The Dark World",
                    "region" : "hollywood",
                    "year" : 2013,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Thor 2 - The Dark World (2013) BRRip [Dual Audio - Eng+Hindi].mkv",
                    "ext" : "mkv",
                    "file_size" : 463237996,
                    "length" : 112,
                    "img" : "img/thor-2.jpg",
                    "imdb_rate" : 7.1,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "The Social Network",
                    "region" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english"],
                    "file_name" : "The Social Network (2010) 1080p BrRip x264 - 1.2GB - YIFY.mp4",
                    "ext" : "mp4",
                    "file_size" : 1289138071,
                    "length" : 120,
                    "img" : "img/the-social-network.jpg",
                    "imdb_rate" : 7.8,
                    "quality" : {"video" : "hd"},
                    "subtitles" : true
                },
                {
                    "name" : "American Gangster",
                    "region" : "hollywood",
                    "year" : 2007,
                    "lang" : ["english", "hindi"],
                    "file_name" : "American Gangster (2007) UNRATED 720p BRRip [Dual-Audio] [Eng-Hindi] TeamTNT ExClusive.mkv",
                    "ext" : "mkv",
                    "file_size" : 1254288727,
                    "length" : 175,
                    "img" : "img/american-gangster.jpg",
                    "imdb_rate" : 7.8,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Saving Private Ryan",
                    "region" : "hollywood",
                    "year" : 1998,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Saving Private Ryan.1998.720p.Hindi.Eng.Dual Audio[~HFR~].mkv",
                    "ext" : "mkv",
                    "file_size" : 1065589921,
                    "length" : 168,
                    "img" : "img/saving-private-ryan.jpg",
                    "imdb_rate" : 8.6,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "The Karate Kid",
                    "region" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english", "hindi"],
                    "file_name" : "The Karate Kid [2010] 720p BRRip [Dual Audio] [English + Hindi] AAC x264 BUZZccd [WBRG].mkv",
                    "ext" : "mkv",
                    "file_size" : 1096872197,
                    "length" : 140,
                    "img" : "img/the-karate-kid.jpg",
                    "imdb_rate" : 6.2,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Coraline",
                    "region" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english"],
                    "file_name" : "[9movies.co.cc]Coraline.2009.DVDRip.x264.scOrp.mkv",
                    "ext" : "mkv",
                    "file_size" : 313362357,
                    "length" : 95,
                    "img" : "img/coraline.jpg",
                    "imdb_rate" : 7.7,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "Ninja Assassin",
                    "region" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Ninja.Hindi_Eng.mkv",
                    "ext" : "mkv",
                    "file_size" : 541865453,
                    "length" : 98,
                    "img" : "img/ninja-assassin.jpg",
                    "imdb_rate" : 6.4,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Step Up 2 The Streets",
                    "region" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english"],
                    "file_name" : "Step Up 2 The Streets 2008.720p.x264.BRRip.GokU61.mp4",
                    "ext" : "mp4",
                    "file_size" : 712915027,
                    "length" : 97,
                    "img" : "img/step-Up-2-The-Streets.jpg",
                    "imdb_rate" : 6.2,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "The Shawshank Redemption",
                    "region" : "hollywood",
                    "year" : 2009,
                    "lang" : ["english"],
                    "file_name" : "The.Shawshank.Redemption.1994.1080p.x264.YIFY.mp4",
                    "ext" : "mp4",
                    "file_size" : 1722009470,
                    "length" : 142,
                    "img" : "img/the-shawshank-redemption.jpg",
                    "imdb_rate" : 9.3,
                    "imdb_id" : "tt0111161",
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "127 Hours",
                    "region" : "hollywood",
                    "year" : 2010,
                    "lang" : ["english"],
                    "file_name" : "127.HRSCR-xvid_MC8.avi",
                    "ext" : "avi",
                    "file_size" : 734978048,
                    "length" : 92,
                    "img" : "img/127-hours.jpg",
                    "imdb_rate" : 7.6,
                    "subtitles" : true,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "Fearless",
                    "region" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english"],
                    "file_name" : "2006 - Jet.Li.Fearless.cd1-Eng.avi",
                    "ext" : "avi",
                    "file_size" : 734109696+734449664,
                    "length" : 104,
                    "img" : "img/fearless.jpg",
                    "imdb_rate" : 7.7,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "300",
                    "region" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english", "hindi"],
                    "file_name" : "300(2006)1080p[Dual Audio] [Eng-Hindi]Current_HD.mkv",
                    "ext" : "mkv",
                    "file_size" : 846027224,
                    "length" : 116,
                    "img" : "img/300.jpg",
                    "imdb_rate" : 7.8,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Spider Man",
                    "region" : "hollywood",
                    "year" : 2002,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Spider Man (2002).avi",
                    "ext" : "avi",
                    "file_size" : 945511668,
                    "length" : 116,
                    "img" : "img/spider-man.jpg",
                    "imdb_rate" : 7.3,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "Fast and Furious 3 Tokyo Drift",
                    "region" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english", "hindi"],
                    "file_name" : "OnlineMoviesFreee.Com.Fat.Furious.2006 (1).mkv",
                    "ext" : "mkv",
                    "file_size" : 666625361,
                    "length" : 97,
                    "img" : "img/fast-and-furious-3-tokyo-drift.jpg",
                    "imdb_rate" : 5.9,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Titanic",
                    "region" : "hollywood",
                    "year" : 1997,
                    "lang" : ["hindi"],
                    "file_name" : "Titanic.1997.mkv",
                    "ext" : "mkv",
                    "file_size" : 570760738,
                    "length" : 186,
                    "img" : "img/titanic.jpg",
                    "imdb_rate" : 7.7,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "Wanted",
                    "region" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Wanted.mkv",
                    "ext" : "mkv",
                    "file_size" : 828850725,
                    "length" : 105,
                    "img" : "img/wanted.jpg",
                    "imdb_rate" : 6.7,
                    "subtitles" : true,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "King Kong",
                    "region" : "hollywood",
                    "year" : 2005,
                    "lang" : ["english", "hindi"],
                    "file_name" : "King Kong 2005 Extended BRRip 720p{Dual audio}[Eng Hindi]Current_HD.mkv",
                    "ext" : "mkv",
                    "file_size" : 1078086425,
                    "length" : 192,
                    "img" : "img/king-kong.jpg",
                    "imdb_rate" : 7.3,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Risky Business",
                    "region" : "hollywood",
                    "year" : 1983,
                    "lang" : ["english"],
                    "file_name" : "Risky Business 1983 DvDrip[Eng]-greenbud1969.avi",
                    "ext" : "avi",
                    "file_size" : 734330880,
                    "length" : 160,
                    "img" : "img/risky-business.jpg",
                    "imdb_rate" : 6.8
                },
                {
                    "name" : "Atlantis The Lost Empire",
                    "region" : "hollywood",
                    "year" : 2001,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Atlantis.The.Lost.Empire/Atlantis.The.Lost.Empire.[2001]720p BRRip [Hindi-Eng]  By K@rtik [ExD Exclucive].mkv",
                    "ext" : "mkv",
                    "file_size" : 846653768,
                    "length" : 95,
                    "img" : "img/Atlantis-The-Lost-Empire.jpg",
                    "imdb_rate" : 6.8,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Black Hawk Down",
                    "region" : "hollywood",
                    //"year" : ,
                    "lang" : ["hindi"],
                    "file_name" : "black hawk down/BHD 1.dat",
                    "ext" : "dat",
                    "file_size" : 705498908,
                    "length" : 132,
                    "img" : "img/Black-Hawk-Down.jpg",
                    "imdb_rate" : 7.7,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Clear and Present Danger",
                    "region" : "hollywood",
                    "year" : 1994,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Clear.and.Present.Danger/Clear.and.Present.Danger (1994) Dvd Rip Dual Audio [Eng-Hindi] [MTR Dev].mkv",
                    "ext" : "mkv",
                    "file_size" : 788522999,
                    "length" : 135,
                    "img" : "img/Clear-and-Present-Danger.jpg",
                    "imdb_rate" : 6.9,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Earthkiller",
                    "region" : "hollywood",
                    "year" : 2011,
                    "lang" : ["english"],
                    "file_name" : "Earthkiller.2011.BRRip.XviD-KAZAN/Earthkiller.2011.BRRip.XviD-KAZAN.avi",
                    "ext" : "avi",
                    "file_size" : 1559764992,
                    "length" : 83,
                    "img" : "img/Earthkiller.jpg",
                    "imdb_rate" : 2.2,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Finding Nemo",
                    "region" : "hollywood",
                    "year" : 2003,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Finding Nemo (2003) BRRip 720p x264 [Dual Audio][Hindi+English]--prisak--{HKRG}/Finding Nemo (2003) BRRip 720p x264 [Dual Audio][Hindi+English]--prisak--{HKRG}.mkv",
                    "ext" : "mkv",
                    "file_size" : 777543717,
                    "length" : 100,
                    "img" : "img/Finding-Nemo.jpg",
                    "imdb_rate" : 8.2,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Gossip Girl",
                    "region" : "hollywood",
                    "year" : 2007,
                    "lang" : ["english"],
                    "file_name" : "Gossip Girl S05E13 HDTV XviD-LOL[ettv]/Gossip.Girl.S05E13.HDTV.XviD-LOL.avi",
                    "ext" : "avi",
                    "file_size" : 366698418,
                    "length" : 41,
                    "img" : "img/Gossip-Girl.jpg",
                    "imdb_rate" : 7.4,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Jumper",
                    "region" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english"],
                    "file_name" : "jumper/",
                    "ext" : "dat",
                    "file_size" : 885880888,
                    "length" : 83,
                    "img" : "img/Jumper.jpg",
                    "imdb_rate" : 6.1,
                    //"quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Men-of-Honor",
                    "region" : "hollywood",
                    "year" : 2000,
                    "lang" : ["english"],
                    "file_name" : "ManOfHonour/",
                    "ext" : "dat",
                    "file_size" : 1310299288,
                    "length" : 123,
                    "img" : "img/Men-of-Honor.jpg",
                    "imdb_rate" : 7.1,
                    //"quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Safe",
                    "region" : "hollywood",
                    "year" : 2012,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Safe (2012) 720p Blu-Ray x264 [Dual-Audio] [English + Hindi] - Mafiaking/Safe (2012) 720p Blu-Ray x264 [Dual-Audio] [English + Hindi] - Mafiaking.mkv",
                    "ext" : "mkv",
                    "file_size" : 875355063,
                    "length" : 94,
                    "img" : "img/Safe.jpg",
                    "imdb_rate" : 6.5,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Scent of a Woman",
                    "region" : "hollywood",
                    "year" : 1992,
                    "lang" : ["english"],
                    "file_name" : "Scent Of a Women/Scent Of A Woman.dat",
                    "ext" : "dat",
                    "file_size" : 633987072,
                    "length" : 156,
                    "img" : "img/Scent-of-a-Woman.jpg",
                    "imdb_rate" : 8,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Sherlock Holmes",
                    "region" : "hollywood",
                    "year" : 2009,
                    "lang" : ["hindi"],
                    "file_name" : "Sherlock Holmes Series/Sherlock Holmes- Aides Police.mkv",
                    "ext" : "mkv",
                    "file_size" : 759840640,
                    "length" : 128,
                    "img" : "img/Sherlock-Holmes.jpg",
                    "imdb_rate" : 7.6,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Terminator 2: Judgment Day",
                    "region" : "hollywood",
                    "year" : 1991,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Terminator 2 - Judgment Day (1991)/Terminator 2 - Judgment Day (1991) 720p BRRip x264 [Dual-Audio] [Eng-Hindi].mkv",
                    "ext" : "mkv",
                    "file_size" : 732802117,
                    "length" : 153,
                    "img" : "img/Terminator-2-Judgment-Day.jpg",
                    "imdb_rate" : 8.5,
                    "quality" : {"video" : "hd"},
                    "subtitles" : true
                },
                {
                    "name" : "Thank You for Smoking",
                    "region" : "hollywood",
                    "year" : 2005,
                    "lang" : ["english"],
                    "file_name" : "Than You For Smoking/Thank.You.For.Smoking[2005].dat",
                    "ext" : "dat",
                    "file_size" : 733949952,
                    "length" : 92,
                    "img" : "img/Thank-You-for-Smoking.jpg",
                    "imdb_rate" : 7.6,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "The Aviator",
                    "region" : "hollywood",
                    "year" : 2004,
                    "lang" : ["english"],
                    "file_name" : "The Aviator-DVDRip[Eng]2004/The Aviator-DVDRip[Eng]2004.avi",
                    "ext" : "avi",
                    "file_size" : 1396817920,
                    "length" : 163,
                    "img" : "img/The-Aviator.jpg",
                    "imdb_rate" : 7.5,
                    "quality" : {"video" : "sd"},
                    "subtitles" : true
                },
                {
                    "name" : "The Core",
                    "region" : "hollywood",
                    "year" : 2003,
                    "lang" : ["english", "hindi"],
                    "file_name" : "The Core (2003)/The Core (2003) [BRRip 720p] [Dual Audio] [Hindi-Eng] by []Omeg@king[].mkv",
                    "ext" : "mkv",
                    "file_size" : 1014778919,
                    "length" : 126,
                    "img" : "img/The-Core.jpg",
                    "imdb_rate" : 5.4,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "The Guardian",
                    "region" : "hollywood",
                    "year" : 2006,
                    "lang" : ["english"],
                    "file_name" : "the guardian/",
                    "ext" : "dat",
                    "file_size" : 1413291016,
                    "length" : 132,
                    "img" : "img/The-Guardian.jpg",
                    "imdb_rate" : 6.8,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "The Lion King",
                    "region" : "hollywood",
                    "year" : 1994,
                    "lang" : ["english", "hindi"],
                    "file_name" : "The Lion King (1994)/The Lion King 720p  x264 AAC BRRip [Dual Audio] [English+Hindi] ~R@ju~ [WBRG].mkv",
                    "ext" : "mkv",
                    "file_size" : 665350597,
                    "length" : 88,
                    "img" : "img/The-Lion-King.jpg",
                    "imdb_rate" : 8.5,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Battleship",
                    "region" : "hollywood",
                    "year" : 2012,
                    "lang" : ["english"],
                    "file_name" : "Battelship (2012) 720p BrRip 870MiB Theroxstar Release",
                    "ext" : "mkv",
                    "file_size" : 914677326,
                    "length" : 131,
                    "img" : "img/Battleship.jpg",
                    "imdb_rate" : 5.9,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Catch Me If You Can",
                    "region" : "hollywood",
                    "year" : 2002,
                    "lang" : ["hindi"],
                    "file_name" : "Catch me if u can 2002 HDTV Rip",
                    "ext" : ".mkv",
                    "file_size" : 846565757,
                    "length" : 132,
                    "img" : "img/Catch-Me-If-You-Can.jpg",
                    "imdb_rate" : 8.0,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Kung Fu Panda",
                    "region" : "hollywood",
                    "year" : 2008,
                    "lang" : ["hindi"],
                    "file_name" : "kumfu panda.vob",
                    "ext" : "vob",
                    "file_size" : 673662976,
                    "length" : 82,
                    "img" : "img/Kung-Fu-Panda.jpg",
                    "imdb_rate" : 7.6,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Madagascar: Escape 2 Africa",
                    "region" : "hollywood",
                    "year" : 2008,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Madagascar Escape 2 Africa.mkv",
                    "ext" : "mkv",
                    "file_size" : 373498754,
                    "length" : 85,
                    "img" : "img/Madagascar-Escape-2-Africa.jpg",
                    "imdb_rate" : 6.7,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Madagascar",
                    "region" : "hollywood",
                    "year" : 2005,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Madagascar.mkv",
                    "ext" : "mkv",
                    "file_size" : 810967158,
                    "length" : 82,
                    "img" : "img/Madagascar.jpg",
                    "imdb_rate" : 6.9,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Ratatouille",
                    "region" : "hollywood",
                    "year" : 2007,
                    "lang" : ["hindi"],
                    "file_name" : "Ratatouille.avi",
                    "ext" : "avi",
                    "file_size" : 671959040,
                    "length" : 110,
                    "img" : "img/Ratatouille.jpg",
                    "imdb_rate" : 8,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Riddick",
                    "region" : "hollywood",
                    "year" : 2013,
                    "lang" : ["english", "hindi"],
                    "file_name" : "Riddick.mkv",
                    "ext" : "mkv",
                    "file_size" : 1042486700,
                    "length" : 118,
                    "img" : "img/Riddick.jpg",
                    "imdb_rate" : 6.4,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Shrek",
                    "region" : "hollywood",
                    "year" : 2001,
                    "lang" : ["hindi"],
                    "file_name" : "Shrek (2001) (In Hindi) - Full Movie - Screen4u.net - It_s Showtime.flv",
                    "ext" : "flv",
                    "file_size" : 363873188,
                    "length" : 86,
                    "img" : "img/Shrek.jpg",
                    "imdb_rate" : 7.9,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                }
            ],
            "directories" : [
                {
                    "name" : "James Bond",
                    "movies" : [
                        {
                            "name" : "James Bond 007: Goldfinger",
                            "region" : "hollywood",
                            "year" : 1964,
                            "lang" : ["english"],
                            "file_name" : "03 - James Bond 007 - Goldfinger [DivX] (1964).avi",
                            "ext" : "avi",
                            "file_size" : 721145856,
                            "length" : 109,
                            "img" : "img/Goldfinger.jpg",
                            "imdb_rate" : 7.8,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Casino Royale",
                            "region" : "hollywood",
                            "year" : 2006,
                            "lang" : ["english"],
                            "file_name" : "Casino.Royale[2006]DvDrip[Eng]-aXXo.avi",
                            //"ext" : "avi",
                            "file_size" : 841349120,
                            "length" : 144,
                            "img" : "img/Casino-Royale.jpg",
                            "imdb_rate" : 8,
                            "quality" : {"video" : "sd"},
                            "subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Diamonds Are Forever",
                            "region" : "hollywood",
                            "year" : 1971,
                            "lang" : ["english"],
                            "file_name" : "Diamonds Are Forever[1971]DvDrip[Eng]-FXG.avi",
                            "ext" : "avi",
                            "file_size" : 733049936,
                            "length" : 120,
                            "img" : "img/Diamonds-Are-Forever.jpg",
                            "imdb_rate" : 6.7,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Dr. No",
                            "region" : "hollywood",
                            "year" : 1962,
                            "lang" : ["english"],
                            "file_name" : "Dr. No[1962]DvDrip[Eng]-FXG.avi",
                            "ext" : "avi",
                            "file_size" : 732494442,
                            "length" : 109,
                            "img" : "img/Dr-No.jpg",
                            "imdb_rate" : 7.3,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: From Russia with Love",
                            "region" : "hollywood",
                            "year" : 1963,
                            "lang" : ["english"],
                            "file_name" : "From Russia with Love[1963]DvDrip[Eng]-FXG.avi",
                            "ext" : "avi",
                            "file_size" : 837305924,
                            "length" : 115,
                            "img" : "img/From-Russia-with-Love.jpg",
                            "imdb_rate" : 7.5,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: GoldenEye",
                            "region" : "hollywood",
                            "year" : 1995,
                            "lang" : ["english"],
                            "file_name" : "GOLDEN EYE(1995)DVDrip-Xvid-5.1CH-AC3={DaBaS}=™.avi",
                            "ext" : "avi",
                            "file_size" : 979804152 ,
                            "length" : 129,
                            "img" : "img/GoldenEye.jpg",
                            "imdb_rate" : 7.2,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: The World Is Not Enough",
                            "region" : "hollywood",
                            "year" : 1999,
                            "lang" : ["english"],
                            "file_name" : "James Bond 007 - The world is not enough (1999) [ENG] [DVDrip].avi",
                            "ext" : "avi",
                            "file_size" : 658843648,
                            "length" : 128,
                            "img" : "img/The-World-Is-Not-Enough.jpg",
                            "imdb_rate" : 6.4,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Tomorrow Never Dies",
                            "region" : "hollywood",
                            "year" : 1997,
                            "lang" : ["english"],
                            "file_name" : "James Bond 007 - Tomorrow Never Dies (1997) [ENG] [DVDrip].avi",
                            "ext" : "avi",
                            "file_size" : 635469312,
                            "length" : 118,
                            "img" : "img/Tomorrow-Never-Dies.jpg",
                            "imdb_rate" : 6.5,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Quantum of Solace",
                            "region" : "hollywood",
                            "year" : 2008,
                            "lang" : ["english"],
                            "file_name" : "Quantum of Solace.[2008].DVDRIP.XVID.[Eng]-DUQA.avi",
                            "ext" : "avi",
                            "file_size" : 734930944,
                            "length" : 101,
                            "img" : "img/Quantum-of-Solace.jpg",
                            "imdb_rate" : 6.7,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: Thunderball",
                            "region" : "hollywood",
                            "year" : 1965,
                            "lang" : ["english"],
                            "file_name" : "Thunderball[1965]DvDrip[Eng]-FXG.avi",
                            "ext" : "avi",
                            "file_size" : 836897034,
                            "length" : 210,
                            "img" : "img/Thunderball.jpg",
                            "imdb_rate" : 7,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        },
                        {
                            "name" : "James Bond 007: You Only Live Twice",
                            "region" : "hollywood",
                            "year" : 1967,
                            "lang" : ["english"],
                            "file_name" : "You Only Live Twice[1967]DvDrip[Eng]-FXG.avi",
                            "ext" : "avi",
                            "file_size" : 732535666,
                            "length" : 116,
                            "img" : "img/You-Only-Live-Twice.jpg",
                            "imdb_rate" : 6.9,
                            "quality" : {"video" : "sd"},
                            //"subtitles" : true
                        }
                    ]
                }
            ]
        },
        {
            "name" : "bollywood",
            "movies" : [
                {
                    "name" : "Saathiya",
                    "region" : "bollywood",
                    "year" : 2002,
                    "lang" : ["hindi"],
                    "file_name" : "Saathiya 2002 DVDrip XviD MP3 [RangerTD].avi",
                    "ext" : "avi",
                    "file_size" : 723744430,
                    "length" : 132,
                    "img" : "img/saathiya.jpg",
                    "imdb_rate" : 3.7,
                    "quality" : {"video" : "sd"}
                },
                {
                    "name" : "PK",
                    "region" : "bollywood",
                    "year" : 2014,
                    "lang" : ["hindi"],
                    "file_name" : "PK (2014) - 720p - mHD - x264 - AC3 - 5.1 - NonRetail - Hindi ~ Cool_Release.mkv",
                    "ext" : "mkv",
                    "file_size" : 1763774283,
                    "length" : 152,
                    "img" : "img/pk.jpg",
                    "imdb_rate" : 8.4,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Rock On!!",
                    "region" : "bollywood",
                    //"year" : 0,
                    "lang" : ["hindi"],
                    "file_name" : "Rock On!!.mkv",
                    "ext" : "mkv",
                    "file_size" : 2346834825,
                    "length" : 145,
                    "img" : "img/rock-on.jpg",
                    "imdb_rate" : 7.9,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Dil Dhadakne Do",
                    "region" : "bollywood",
                    "year" : 2015,
                    "lang" : ["hindi"],
                    "file_name" : "Dil Dhadakne Do (2015).mp4",
                    "ext" : "mp4",
                    "file_size" : 943660640,
                    "length" : 162,
                    "img" : "img/dil-dhadakne-do.jpg",
                    "imdb_rate" : 6.9
                },
                {
                    "name" : "Tanu Weds Manu Returns",
                    "region" : "bollywood",
                    "year" : 2015,
                    "lang" : ["hindi"],
                    "file_name" : "Tanu Weds Manu Returns (2015).mkv",
                    "ext" : "mkv",
                    "file_size" : 723432159,
                    "length" : 128,
                    "img" : "img/tanu-weds-manu-returns.jpg",
                    "imdb_rate" : 8.3
                },
                {
                    "name" : "Khichdi The Movie",
                    "region" : "bollywood",
                    "year" : 2010,
                    "lang" : ["hindi"],
                    "file_name" : "Khichdi The Movie/Khichdi The Movie (2010) - (797 MB) - BRRip - 720p - X264 - AAC ~=[101]=~ [TMRG].mkv",
                    "ext" : "mkv",
                    "file_size" : 835734800,
                    "length" : 116,
                    "img" : "img/khichdi-the-movie.jpeg",
                    "imdb_rate" : 7,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Queen",
                    "region" : "bollywood",
                    "year" : 2014,
                    "lang" : ["hindi"],
                    "file_name" : "Queen/Queen 2014 Hindi 720p DvDRip x264 AAC...Hon3y.mkv",
                    "ext" : "mkv",
                    "file_size" : 1073593482,
                    "length" : 145,
                    "img" : "img/queen.jpg",
                    "imdb_rate" : 8.5,
                    "quality" : {"video" : "hd"},
                    "subtitles" : true
                },
                {
                    "name" : "Tanu Weds Manu",
                    "region" : "bollywood",
                    "year" : 2011,
                    "lang" : ["hindi"],
                    "file_name" : "Tanu Weds Manu/Tanu Weds Manu 2011 720p BRRip CharmeLeon SilverRG.mkv",
                    "ext" : "mkv",
                    "file_size" : 840284757,
                    "length" : 119,
                    "img" : "img/tanu-weds-manu.jpg",
                    "imdb_rate" : 6.4,
                    "quality" : {"video" : "hd"},
                    "subtitles" : true
                },
                {
                    "name" : "Creature 3D",
                    "region" : "bollywood",
                    "year" : 2014,
                    "lang" : ["hindi"],
                    "file_name" : "Creature 3D.mkv",
                    "ext" : "mkv",
                    "file_size" : 734897038,
                    "length" : 129,
                    "img" : "img/creature-3d.jpg",
                    "imdb_rate" : 3.1,
                    //"quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Hate Story",
                    "region" : "bollywood",
                    "year" : 2012,
                    "lang" : ["hindi"],
                    "file_name" : "Hate Story (2012)Hindi 950MB 720P Webrip x264 Team DDH~RG.mp4",
                    "ext" : "mp4",
                    "file_size" : 997669344,
                    "length" : 131,
                    "img" : "img/hate-story.jpg",
                    "imdb_rate" : 5.1,
                    "quality" : {"video" : "hd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Roar",
                    "region" : "bollywood",
                    "year" : 2014,
                    "lang" : ["hindi"],
                    "file_name" : "roar.avi",
                    "ext" : "avi",
                    "file_size" : 730965302,
                    "length" : 118,
                    "img" : "img/roar.jpg",
                    "imdb_rate" : 5.8,
                    //"quality" : {"video" : "hd"},
                    //"subtitles" : true
                }
            ]
        },
        {
            "name" : "tollywood",
            "movies" : [
                {
                    "name" : "Rebel",
                    "region" : "tollywood",
                    "year" : 2012,
                    "lang" : ["hindi", "other"],
                    "file_name" : "Rebel (2012)  m-HD  720p  Hindi  Telugu  BHATTI87.mkv",
                    "ext" : "mkv",
                    "file_size" : 2823101205,
                    "length" : 170,
                    "img" : "img/rebel.jpg",
                    "imdb_rate" : 4.1,
                    "quality" : {"video" : "hd"}
                },
                {
                    "name" : "Business Man",
                    "region" : "tollywood",
                    "year" : 2012,
                    "lang" : ["hindi", "other"],
                    "file_name" : "Business Man (2012).mkv",
                    "ext" : "mkv",
                    "file_size" : 413601668,
                    "length" : 131,
                    "img" : "img/business-man.jpg",
                    "imdb_rate" : 7.1,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Oosaravelli",
                    "region" : "tollywood",
                    "year" : 2011,
                    "lang" : ["hindi", "other"],
                    "file_name" : "Oosaravelli-Mar Mitenge (2011) BRRip x264 [Dual-Audio] [Telugu-Hindi] [395MB].mkv",
                    "ext" : "mkv",
                    "file_size" : 412023067,
                    "length" : 165,
                    "img" : "img/oosaravelli.jpg",
                    "imdb_rate" : 6.3,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                },
                {
                    "name" : "Singam 2",
                    "region" : "tollywood",
                    "year" : 2013,
                    "lang" : ["hindi", "other"],
                    "file_name" : "Singam 2 (2013) - Dual Audio - [Tamil-Hindi] - x264 - AAC - Team SR.mkv",
                    "ext" : "mkv",
                    "file_size" : 1454920414,
                    "length" : 158,
                    "img" : "img/singam-2-tollywood.jpg",
                    "imdb_rate" : 6.2,
                    "quality" : {"video" : "sd"},
                    //"subtitles" : true
                }
            ]
        }
    ]
};
